version: '3'
services:
  
  influxdb:
    build:
      context: .
      dockerfile: Dockerfile.influxdb
    ports:
      - "8086:8086"
  
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    links:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
  
  k6:
    build:
      context: .
      dockerfile: Dockerfile.k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    command: 'version'
    links:
      - web
  
  test:
   build:
     context: .
     dockerfile: Dockerfile.test
   container_name: test
   links:
      - web
    
  web:
   build:
    context: .
    dockerfile: Dockerfile.webservice
   container_name: web
   links:
     - redis
   ports:
     - "9300:9300"
   expose:
     - "9300"
    
  redis:
   image: redis
